---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: 信頼性の高い運用を実現するために、 Cloud Volumes ONTAP には AWS にストレージ構成の制限があります。最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。 
---
= AWS のストレージの制限
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP には、安定した運用を実現するために、ストレージ構成の制限があります最大のパフォーマンスを得るためには、システムを最大値で構成しないでください。



== ライセンス別の最大システム容量

Cloud Volumes ONTAP システムの最大システム容量はライセンスで決まります。最大システム容量には、ディスクベースのストレージに加えて、データの階層化に使用されるオブジェクトストレージが含まれます。ネットアップはこの制限を超えてもサポートしていません。

一部の HA 構成では、ディスク制限により、ディスクのみを使用することで容量制限に達することができません。その場合、で容量の制限に達することができます https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。詳細については、以下の容量とディスクの制限を参照してください。

[cols="25,75"]
|===
| 使用許諾 | 最大システム容量（ディスク + オブジェクトストレージ） 


| フリーミアム | 500 GiB 


| PAYGO Explore | 2TiB （ Explore ではデータ階層化はサポートされません） 


| PAYGO Standard の略 | 10TiB 


| PAYGO Premium | 368TiB 


| ノードベースのライセンス | 1 ライセンスあたり 368 TiB 


| 容量単位のライセンスです | 2 PiB 
|===


===== HA の場合、ライセンスの容量制限はノード単位か、 HA ペア全体に適用されるか

容量制限は HA ペア全体の容量制限です。ノード単位ではありません。たとえば、 Premium ライセンスを使用する場合、両方のノード間で最大 368 TiB の容量を確保できます。



===== AWS の HA システムでは、ミラーリングされたデータは容量制限にカウントされますか。

いいえ、できません。AWS HA ペアのデータは、障害発生時にデータを利用できるように、ノード間で同期的にミラーされます。たとえば、ノード A で 8TiB ディスクを購入した場合、 Cloud Manager は、ミラーリングされたデータに使用する 8 TiB のディスクをノード B にも割り当てます。16TiB の容量がプロビジョニングされましたが、ライセンスの上限には 8TiB しかカウントされません。



== ディスクおよび階層化の制限は EC2 インスタンスごとに適用されます

Cloud Volumes ONTAP は EBS ボリュームをディスクとして使用し、最大ディスクサイズは 16TiB です。以下のセクションでは、 EC2 インスタンスタイプごとにディスクと階層化の制限を示します。これは、多くの EC2 インスタンスタイプでディスクの制限が異なるためです。また、シングルノードシステムと HA ペアではディスク制限も異なります。

以下のディスク制限は、ユーザデータが格納されたディスクに固有です。この制限には、ブートディスクとルートディスクは含まれていません。


NOTE: Cloud Volumes ONTAP BYOL システムに複数のノードベースライセンスを購入して、 368 TiB を超える容量を割り当てることができるようになりました。シングルノードシステムまたは HA ペアに対して購入できるライセンスの数に制限はありません。ディスク制限によって、ディスクだけを使用することで容量制限に達することがないことに注意してください。を使用すると、ディスク制限を超えることができます https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["使用頻度の低いデータをオブジェクトストレージに階層化します"^]。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volume にシステムライセンスを追加する方法について説明します ONTAP"^]。



=== Premium ライセンスがあるシングルノード

[cols="18,18,32,32"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 22 | 352TiB | 368TiB 


| C4 、 M4 、および R4 インスタンス | 34 | 368TiB | 368TiB 
|===


=== ノードベースのライセンスを使用するシングルノード

[cols="18,18,16,16,16,16"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 2+| 最大システム容量（ 1 ライセンス 2+| 複数のライセンスを持つ最大システム容量 


2+|  | * ディスクのみ * | * ディスク + データ階層化 * | * ディスクのみ * | * ディスク + データ階層化 * 


| C5 、 m5 、および r5 インスタンス | 22 | 352TiB | 368TiB | 352TiB | 1 ライセンスあたり 368 TiB 


| C4 、 M4 、および R4 インスタンス | 34 | 368TiB | 368TiB | 544 TiB | 1 ライセンスあたり 368 TiB 
|===


=== 容量単位のライセンスがあるシングルノード

[cols="18,18,32,32"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 22 | 352TiB | 2 PiB 


| C4 、 M4 、および R4 インスタンス | 34 | 544 TiB | 2 PiB 
|===


=== Premium ライセンスがある HA ペア

[cols="18,18,32,32"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 19 | 304 TiB | 368TiB 


| C4 、 M4 、および R4 インスタンス | 31. | 368TiB | 368TiB 
|===


=== ノードベースのライセンスが設定された HA ペア

[cols="18,18,16,16,16,16"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 2+| 最大システム容量（ 1 ライセンス 2+| 複数のライセンスを持つ最大システム容量 


2+|  | * ディスクのみ * | * ディスク + データ階層化 * | * ディスクのみ * | * ディスク + データ階層化 * 


| C5 、 m5 、および r5 インスタンス | 19 | 304 TiB | 368TiB | 304 TiB | 1 ライセンスあたり 368 TiB 


| C4 、 M4 、および R4 インスタンス | 31. | 368TiB | 368TiB | 496TiB | 1 ライセンスあたり 368 TiB 
|===


=== 容量ベースのライセンスが設定された HA ペア

[cols="18,18,32,32"]
|===
| インスタンスファミリー | ノードあたりの最大ディスク数 | ディスクのみの場合の最大システム容量 | ディスクとデータ階層化による最大システム容量 


| C5 、 m5 、および r5 インスタンス | 19 | 304 TiB | 2 PiB 


| C4 、 M4 、および R4 インスタンス | 31. | 496TiB | 2 PiB 
|===


== アグリゲートの制限

Cloud Volumes ONTAP は AWS ボリュームをディスクとして使用し、これらを _Aggregate__ にグループ化します。アグリゲートは、ボリュームにストレージを提供します。

[cols="2*"]
|===
| パラメータ | 制限（ Limit ） 


| アグリゲートの最大数 | 1 つのノード：ディスクリミットの HA ペアと同じです：ノード ^1 の 18 


| 最大アグリゲートサイズ | 96 TiB の物理容量 ^2^ 


| アグリゲートあたりのディスク数 | 1-6^3^ 


| アグリゲートあたりの RAID グループの最大数 | 1. 
|===
注：

. HA ペアの両方のノードに 19 個のアグリゲートを作成することはできません。これは、作成するとデータディスクの制限を超えてしまうためです。
. アグリゲートの容量の制限は、アグリゲートを構成するディスクに基づいています。データの階層化に使用されるオブジェクトストレージは制限に含まれません。
. アグリゲート内のディスクはすべて同じサイズである必要があります。




== 論理ストレージの制限

[cols="22,22,56"]
|===
| 論理ストレージ | パラメータ | 制限（ Limit ） 


| * Storage VM （ SVM ） * | Cloud Volumes ONTAP の最大数 （ HA ペアまたはシングルノード）  a| 
* BYOL * を使用した C5 、 M5 、 R5 の各インスタンスは、独自のライセンスを使用する場合、 C5 、 M5 、 R5 の各インスタンスタイプでサポートされます。

* 12 個の Storage VM とシングルノードシステム
* HA ペアの Storage VM × 8



NOTE: Storage VM は Cloud Volumes ONTAP システム全体（ HA ペアまたはシングルノード）にまたがります。

Cloud Volumes ONTAP に付属する最初の Storage VM に追加する _data-pサービング _svm のそれぞれに、デフォルトでアドオンライセンスが必要です。アカウントチームに連絡して SVM アドオンライセンスを入手してください。

ディザスタリカバリ（ DR ）用に設定する Storage VM には追加ライセンスは必要ありませんが（無償）、 Storage VM の数は制限に含まれます。^ 1 、 2 、 ^

* その他のすべての構成 * 1 つのデータ提供用 Storage VM と 1 つのディザスタリカバリ用デスティネーション Storage VM がサポートされています。^2^

Storage VM は Cloud Volumes ONTAP システム全体（ HA ペアまたはシングルノード）にまたがります。



.2+| * ファイル * | 最大サイズ | 16TiB 


| ボリュームあたりの最大数 | ボリュームサイズは最大 20 億個です 


| * FlexClone ボリューム * | クローン階層の深さ ^3^ | 499 


.3+| * FlexVol ボリューム * | ノードあたりの最大数 | 500 


| 最小サイズ | 20 MB 


| 最大サイズ | 100TiB 


| * qtree * | FlexVol あたりの最大数 | 4,995 


| * Snapshot コピー * | FlexVol あたりの最大数 | 1,023 
|===
注：

. たとえば、 HA ペアにデータを提供している Storage VM が 8 台ある場合、上限に達し、追加で Storage VM を作成できなくなります。これは、ディザスタリカバリ用に 8 台の Storage VM が設定された別の HA ペアについても同様です。この制限に達しており、追加の Storage VM を作成できません。
. ソース Storage VM で障害が発生した場合は、デスティネーション Storage VM をデータアクセス用にアクティブ化できます。Cloud Manager では、 Storage VM ディザスタリカバリのセットアップやオーケストレーションはサポートされていません。System Manager または CLI を使用する必要があります。
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["SVM ディザスタリカバリ設定エクスプレスガイド"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["『 SVM ディザスタリカバリエクスプレスガイド』"^]


. クローン階層の深さは、 1 つの FlexVol から作成できる、ネストされた FlexClone ボリュームの最大階層です。




== iSCSI ストレージの制限

[cols="3*"]
|===
| iSCSI ストレージ | パラメータ | 制限（ Limit ） 


.4+| * LUN* | ノードあたりの最大数 | 1,024 


| LUN マップの最大数 | 1,024 


| 最大サイズ | 16TiB 


| ボリュームあたりの最大数 | 512 


| * igroup 数 * | ノードあたりの最大数 | 256 


.2+| * イニシエータ * | ノードあたりの最大数 | 512 


| igroup あたりの最大数 | 128 


| * iSCSI セッション * | ノードあたりの最大数 | 1,024 


.2+| * LIF * | ポートあたりの最大数 | 32 


| ポートセットあたりの最大数 | 32 


| * ポートセット * | ノードあたりの最大数 | 256 
|===